let space1 = `x`;
let space2 = `o`;
let space3 = 'x';
let space4 = `o`;
let space5 = `x`;
let space6 = `o`;
let space7 = `x`;
let space8 = `o`;
let space9 = `x`;

console.log('  |    |   ');
console.log(` ${space1}  | ${space2}  |  `);
console.log(`  |    |   `);
console.log(`-----------`);
console.log(`  |    |   `);
console.log(` ${space3}  | ${space5}  |  `);
console.log(`   |   |    `);
console.log(`------------`);
console.log(`   |   |    `);
console.log(` ${space8}  |  |    `);
console.log(`   |   |   `);